---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bamboo-agent
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: bamboo-agent
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: bamboo-agent
subjects:
- kind: ServiceAccount
  name: bamboo-agent
  namespace: default
roleRef:
  kind: Role
  name: bamboo-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: bamboo-agent
  name: bamboo-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: bamboo-agent
  template:
    metadata:
      labels:
        k8s-app: bamboo-agent
    spec:
      serviceAccount: bamboo-agent
      volumes:
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: agent-data
        emptyDir: {}
      containers:
      - name: bamboo
        image: cpowers/bamboo-agent:latest
        args: ["http://bamboo.default.svc.cluster.local"]
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /home/bamboo/bamboo-agent-home
          name: agent-data