kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-hdd-retain
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-hdd
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed